Repository SKopecz/PositiveIntegrators.jl, pull requests merged in 2024-07, with the labels that each got.

#88 fix edit URL of license in docs
  docs/make.jl
Labels: bug, documentation

#92 Create Downgrade.yml
  .github/workflows/CI.yml
  .github/workflows/Downgrade.yml
  Project.toml
  test/Project.toml
Labels: dependencies

#91 Update NEWS.md
  NEWS.md
Labels: documentation

#93 Update README.md
  README.md
Labels: documentation

#102 remove PositiveIntegrators from docs/Project.toml
  docs/Project.toml
Labels: documentation

#101 improve performance with sparse matrices
  docs/Project.toml
  docs/make.jl
  docs/src/faq.md
  docs/src/linear_advection.md
  src/PositiveIntegrators.jl
  src/mprk.jl
  src/proddest.jl
  src/sspmprk.jl
  test/runtests.jl
Labels: performance

#105 add heat equation tutorial
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/heat_equation_dirichlet.md
  docs/src/heat_equation_neumann.md
Labels: documentation

#104 Remove `d_prototype` & create type tests for `p_prototype`
  NEWS.md
  Project.toml
  src/mprk.jl
  src/proddest.jl
  src/sspmprk.jl
  test/runtests.jl
Labels: breaking

#111 Order API reference
  docs/src/api_reference.md
Labels: documentation
